/** Declaration file generated by dts-gen */

export = restify_jwt_community;

declare function restify_jwt_community(options: any): any;

declare namespace restify_jwt_community {
    const prototype: {
    };

}

